package com.test;

import com.main.RomanStringBuilder;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import java.util.Arrays;
import java.util.Collection;

import static org.junit.Assert.*;

/**
 * Created by raphael on 13/01/2018.
 */
@RunWith(Parameterized.class)
public class RomanStringBuilderTest {



    private int input;
    private String expectedResult;


    public RomanStringBuilderTest(int input, String expectedResult)
    {
        this.input = input;
        this.expectedResult = expectedResult;
    }

    @Parameterized.Parameters
    public static Collection executeTests()
    {
        // Correct sequence of roman numerals and their arabic equivalents
        // (found on : https://www.calculateme.com/cRomanNumerals/ArabicNumeralsToRoman.htm)
        return Arrays.asList(new Object[][] {
                {1, "I"},
                {2, "II"},
                {3, "III"},
                {4, "IV"},
                {5, "V"},
                {6, "VI"},
                {7, "VII"},
                {8, "VIII"},
                {9, "IX"},
                {10, "X"},
                {11, "XI"},
                {12, "XII"},
                {13, "XIII"},
                {14, "XIV"},
                {15, "XV"},
                {16, "XVI"},
                {17, "XVII"},
                {18, "XVIII"},
                {19, "XIX"},
                {20, "XX"},
                {21, "XXI"},
                {22, "XXII"},
                {23, "XXIII"},
                {24, "XXIV"},
                {25, "XXV"},
                {26, "XXVI"},
                {27, "XXVII"},
                {28, "XXVIII"},
                {29, "XXIX"},
                {30, "XXX"},
                {31, "XXXI"},
                {32, "XXXII"},
                {33, "XXXIII"},
                {34, "XXXIV"},
                {35, "XXXV"},
                {36, "XXXVI"},
                {37, "XXXVII"},
                {38, "XXXVIII"},
                {39, "XXXIX"},
                {40, "XL"},
                {41, "XLI"},
                {42, "XLII"},
                {43, "XLIII"},
                {44, "XLIV"},
                {45, "XLV"},
                {46, "XLVI"},
                {47, "XLVII"},
                {48, "XLVIII"},
                {49, "XLIX"},
                {50, "L"},
                {51, "LI"},
                {52, "LII"},
                {53, "LIII"},
                {54, "LIV"},
                {55, "LV"},
                {56, "LVI"},
                {57, "LVII"},
                {58, "LVIII"},
                {59, "LIX"},
                {60, "LX"},
                {61, "LXI"},
                {62, "LXII"},
                {63, "LXIII"},
                {64, "LXIV"},
                {65, "LXV"},
                {66, "LXVI"},
                {67, "LXVII"},
                {68, "LXVIII"},
                {69, "LXIX"},
                {70, "LXX"},
                {71, "LXXI"},
                {72, "LXXII"},
                {73, "LXXIII"},
                {74, "LXXIV"},
                {75, "LXXV"},
                {76, "LXXVI"},
                {77, "LXXVII"},
                {78, "LXXVIII"},
                {79, "LXXIX"},
                {80, "LXXX"},
                {81, "LXXXI"},
                {82, "LXXXII"},
                {83, "LXXXIII"},
                {84, "LXXXIV"},
                {85, "LXXXV"},
                {86, "LXXXVI"},
                {87, "LXXXVII"},
                {88, "LXXXVIII"},
                {89, "LXXXIX"},
                {90, "XC"},
                {91, "XCI"},
                {92, "XCII"},
                {93, "XCIII"},
                {94, "XCIV"},
                {95, "XCV"},
                {96, "XCVI"},
                {97, "XCVII"},
                {98, "XCVIII"},
                {99, "XCIX"},
                {100, "C"},
                {101, "CI"},
                {102, "CII"},
                {103, "CIII"},
                {104, "CIV"},
                {105, "CV"},
                {106, "CVI"},
                {107, "CVII"},
                {108, "CVIII"},
                {109, "CIX"},
                {110, "CX"},
                {111, "CXI"},
                {112, "CXII"},
                {113, "CXIII"},
                {114, "CXIV"},
                {115, "CXV"},
                {116, "CXVI"},
                {117, "CXVII"},
                {118, "CXVIII"},
                {119, "CXIX"},
                {120, "CXX"},
                {121, "CXXI"},
                {122, "CXXII"},
                {123, "CXXIII"},
                {124, "CXXIV"},
                {125, "CXXV"},
                {126, "CXXVI"},
                {127, "CXXVII"},
                {128, "CXXVIII"},
                {129, "CXXIX"},
                {130, "CXXX"},
                {131, "CXXXI"},
                {132, "CXXXII"},
                {133, "CXXXIII"},
                {134, "CXXXIV"},
                {135, "CXXXV"},
                {136, "CXXXVI"},
                {137, "CXXXVII"},
                {138, "CXXXVIII"},
                {139, "CXXXIX"},
                {140, "CXL"},
                {141, "CXLI"},
                {142, "CXLII"},
                {143, "CXLIII"},
                {144, "CXLIV"},
                {145, "CXLV"},
                {146, "CXLVI"},
                {147, "CXLVII"},
                {148, "CXLVIII"},
                {149, "CXLIX"},
                {150, "CL"},
                {151, "CLI"},
                {152, "CLII"},
                {153, "CLIII"},
                {154, "CLIV"},
                {155, "CLV"},
                {156, "CLVI"},
                {157, "CLVII"},
                {158, "CLVIII"},
                {159, "CLIX"},
                {160, "CLX"},
                {161, "CLXI"},
                {162, "CLXII"},
                {163, "CLXIII"},
                {164, "CLXIV"},
                {165, "CLXV"},
                {166, "CLXVI"},
                {167, "CLXVII"},
                {168, "CLXVIII"},
                {169, "CLXIX"},
                {170, "CLXX"},
                {171, "CLXXI"},
                {172, "CLXXII"},
                {173, "CLXXIII"},
                {174, "CLXXIV"},
                {175, "CLXXV"},
                {176, "CLXXVI"},
                {177, "CLXXVII"},
                {178, "CLXXVIII"},
                {179, "CLXXIX"},
                {180, "CLXXX"},
                {181, "CLXXXI"},
                {182, "CLXXXII"},
                {183, "CLXXXIII"},
                {184, "CLXXXIV"},
                {185, "CLXXXV"},
                {186, "CLXXXVI"},
                {187, "CLXXXVII"},
                {188, "CLXXXVIII"},
                {189, "CLXXXIX"},
                {190, "CXC"},
                {191, "CXCI"},
                {192, "CXCII"},
                {193, "CXCIII"},
                {194, "CXCIV"},
                {195, "CXCV"},
                {196, "CXCVI"},
                {197, "CXCVII"},
                {198, "CXCVIII"},
                {199, "CXCIX"},
                {200, "CC"},
                {1900, "MCM"},
                {1901, "MCMI"},
                {1902, "MCMII"},
                {1903, "MCMIII"},
                {1904, "MCMIV"},
                {1905, "MCMV"},
                {1906, "MCMVI"},
                {1907, "MCMVII"},
                {1908, "MCMVIII"},
                {1909, "MCMIX"},
                {1910, "MCMX"},
                {1911, "MCMXI"},
                {1912, "MCMXII"},
                {1913, "MCMXIII"},
                {1914, "MCMXIV"},
                {1915, "MCMXV"},
                {1916, "MCMXVI"},
                {1917, "MCMXVII"},
                {1918, "MCMXVIII"},
                {1919, "MCMXIX"},
                {1920, "MCMXX"},
                {1921, "MCMXXI"},
                {1922, "MCMXXII"},
                {1923, "MCMXXIII"},
                {1924, "MCMXXIV"},
                {1925, "MCMXXV"},
                {1926, "MCMXXVI"},
                {1927, "MCMXXVII"},
                {1928, "MCMXXVIII"},
                {1929, "MCMXXIX"},
                {1930, "MCMXXX"},
                {1931, "MCMXXXI"},
                {1932, "MCMXXXII"},
                {1933, "MCMXXXIII"},
                {1934, "MCMXXXIV"},
                {1935, "MCMXXXV"},
                {1936, "MCMXXXVI"},
                {1937, "MCMXXXVII"},
                {1938, "MCMXXXVIII"},
                {1939, "MCMXXXIX"},
                {1940, "MCMXL"},
                {1941, "MCMXLI"},
                {1942, "MCMXLII"},
                {1943, "MCMXLIII"},
                {1944, "MCMXLIV"},
                {1945, "MCMXLV"},
                {1946, "MCMXLVI"},
                {1947, "MCMXLVII"},
                {1948, "MCMXLVIII"},
                {1949, "MCMXLIX"},
                {1950, "MCML"},
                {1951, "MCMLI"},
                {1952, "MCMLII"},
                {1953, "MCMLIII"},
                {1954, "MCMLIV"},
                {1955, "MCMLV"},
                {1956, "MCMLVI"},
                {1957, "MCMLVII"},
                {1958, "MCMLVIII"},
                {1959, "MCMLIX"},
                {1960, "MCMLX"},
                {1961, "MCMLXI"},
                {1962, "MCMLXII"},
                {1963, "MCMLXIII"},
                {1964, "MCMLXIV"},
                {1965, "MCMLXV"},
                {1966, "MCMLXVI"},
                {1967, "MCMLXVII"},
                {1968, "MCMLXVIII"},
                {1969, "MCMLXIX"},
                {1970, "MCMLXX"},
                {1971, "MCMLXXI"},
                {1972, "MCMLXXII"},
                {1973, "MCMLXXIII"},
                {1974, "MCMLXXIV"},
                {1975, "MCMLXXV"},
                {1976, "MCMLXXVI"},
                {1977, "MCMLXXVII"},
                {1978, "MCMLXXVIII"},
                {1979, "MCMLXXIX"},
                {1980, "MCMLXXX"},
                {1981, "MCMLXXXI"},
                {1982, "MCMLXXXII"},
                {1983, "MCMLXXXIII"},
                {1984, "MCMLXXXIV"},
                {1985, "MCMLXXXV"},
                {1986, "MCMLXXXVI"},
                {1987, "MCMLXXXVII"},
                {1988, "MCMLXXXVIII"},
                {1989, "MCMLXXXIX"},
                {1990, "MCMXC"},
                {1991, "MCMXCI"},
                {1992, "MCMXCII"},
                {1993, "MCMXCIII"},
                {1994, "MCMXCIV"},
                {1995, "MCMXCV"},
                {1996, "MCMXCVI"},
                {1997, "MCMXCVII"},
                {1998, "MCMXCVIII"},
                {1999, "MCMXCIX"},
                {2000, "MM"},
                {2001, "MMI"},
                {2002, "MMII"},
                {2003, "MMIII"},
                {2004, "MMIV"},
                {2005, "MMV"},
                {2006, "MMVI"},
                {2007, "MMVII"},
                {2008, "MMVIII"},
                {2009, "MMIX"},
                {2010, "MMX"},
                {2011, "MMXI"},
                {2012, "MMXII"},
                {2013, "MMXIII"},
                {2014, "MMXIV"},
                {2015, "MMXV"},
                {2016, "MMXVI"},
                {2017, "MMXVII"},
                {2018, "MMXVIII"},
                {2019, "MMXIX"},
                {2020, "MMXX"},
                {2021, "MMXXI"},
                {2022, "MMXXII"},
                {2023, "MMXXIII"},
                {2024, "MMXXIV"},
                {2025, "MMXXV"},
                {2026, "MMXXVI"},
                {2027, "MMXXVII"},
                {2028, "MMXXVIII"},
                {2029, "MMXXIX"},
                {2030, "MMXXX"},
                {2031, "MMXXXI"},
                {2032, "MMXXXII"},
                {2033, "MMXXXIII"},
                {2034, "MMXXXIV"},
                {2035, "MMXXXV"},
                {2036, "MMXXXVI"},
                {2037, "MMXXXVII"},
                {2038, "MMXXXVIII"},
                {2039, "MMXXXIX"},
                {2040, "MMXL"},
                {2041, "MMXLI"},
                {2042, "MMXLII"},
                {2043, "MMXLIII"},
                {2044, "MMXLIV"},
                {2045, "MMXLV"},
                {2046, "MMXLVI"},
                {2047, "MMXLVII"},
                {2048, "MMXLVIII"},
                {2049, "MMXLIX"},
                {2050, "MML"}
        });
    }

    @Test
    public void testParsing()
    {
        System.out.println("Testing with : " + input);
        RomanStringBuilder rsb = new RomanStringBuilder(input);
        rsb.ParseArabicToRoman();
        assertTrue(expectedResult.equals(rsb.GetRoman().toString()));
    }



}